export const BOARD_ROOT='https://table-live-by-iwanto-zhang-default-rtdb.firebaseio.com/juicyTableLive/JUICY-HUNTSVILLE/flexibleFloorV1';
const txt=v=>String(v??'');
export const PHYSICAL_TABLE_IDS=['A1','A2','A3','A4','B1','B2','B3','Bar 1','Bar 2','Bar 3','Bar 4','Bar 5','Bar 6','Bar 7','Bar 8','Bar 9','Bar 10','Bar 11','Bar 12','C1','C2','C3','C4','D1','D2','D3','E1','E2','E3','E4','E5','F1','F2','F3','F4','F5','F6','H1','H2','H3','H4','L1','L2','L3','L4','L5','L6','M1','M2','R1','R2','R3','R4','R5','R6','R7'];

export const iso=d=>{const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}`};
function restaurantParts(d=new Date()){const p=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit',weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return{date:`${p.year}-${p.month}-${p.day}`,weekday:p.weekday,hour:+p.hour,minute:+p.minute}}
export const today=()=>restaurantParts().date;
export function dateShiftNow(d=new Date()){const p=restaurantParts(d),weekendSwitch=['Sun','Fri','Sat'].includes(p.weekday),mins=p.hour*60+p.minute;return mins>=(weekendSwitch?15*60+30:16*60)?'PM':'AM'}
export function boardKeyNow(d=new Date()){return `${restaurantParts(d).date}_${dateShiftNow(d)}`}
function asArray(v,len=80){if(Array.isArray(v))return v;const a=Array(len).fill(null);Object.entries(v||{}).forEach(([k,x])=>{if(/^\d+$/.test(k))a[+k]=x});return a}
function epochFromEntry(v){const m=txt(v).match(/seat_(\d{10,13})_/);if(!m)return 0;let n=+m[1];if(n<1e12)n*=1000;return n}
function centralClock(ms){if(!ms)return null;const p=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(ms)).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return{hour:+p.hour,minute:+p.minute}}
function normalizeEvent(e,date,shift,source='ARCHIVE'){if(!e)return null;let seatedAt=Number(e.seatedAt||0)||epochFromEntry(e.entryId||e.id),cc=centralClock(seatedAt);let hour=Number.isInteger(Number(e.hour))?Number(e.hour):(cc?cc.hour:null);return {id:txt(e.entryId||e.id)||`${date}_${shift}_${e.row}_${e.turn}_${e.table}`,entryId:txt(e.entryId||e.id),date:txt(e.date||date),shift:txt(e.shift||shift),server:txt(e.server||'Unknown'),section:txt(e.section||''),table:txt(e.table||''),people:Math.max(0,Number(e.people)||0),rotationSlots:Math.max(1,Number(e.rotationSlots)||Math.ceil(Math.max(1,Number(e.people)||0)/4)),seatedAt,hour:Number.isInteger(hour)?hour:null,source}}
function archiveEvents(snapshot,key){const m=key.match(/^(\d{4}-\d{2}-\d{2})_(AM|PM)$/);if(!m||!snapshot)return[];const raw=Array.isArray(snapshot.events)?snapshot.events:Object.values(snapshot.events||{});return raw.map(e=>normalizeEvent(e,m[1],m[2],'ARCHIVE')).filter(Boolean)}
function liveEvents(board,key){const m=key.match(/^(\d{4}-\d{2}-\d{2})_(AM|PM)$/);if(!m||!board)return[];const out=[];asArray(board.rows,30).forEach((row,ri)=>{if(!row)return;asArray(row.turns,80).forEach((t,ti)=>{if(!t||t.skipped||!t.table)return;out.push(normalizeEvent({...t,server:row.server,section:row.section,row:ri,turn:ti},m[1],m[2],'LIVE'))})});return out.filter(Boolean)}
function mergeEvents(analytics,boards){const map=new Map;Object.entries(analytics||{}).forEach(([k,s])=>archiveEvents(s,k).forEach(e=>map.set(e.id||`${e.date}|${e.shift}|${e.table}|${e.seatedAt}`,e)));Object.entries(boards||{}).forEach(([k,b])=>liveEvents(b,k).forEach(e=>map.set(e.id||`${e.date}|${e.shift}|${e.table}|${e.seatedAt}`,e)));return [...map.values()].sort((a,b)=>(a.date+a.shift).localeCompare(b.date+b.shift)||a.seatedAt-b.seatedAt)}
export function operationalTableStatus(state){const raw=txt(state?.status||'ready').trim().toLowerCase();if(raw==='seated')return'seated';if(raw==='reserved')return'reserved';if(raw==='cleaning'||raw==='clean')return'cleaning';return'ready'}
function liveFloor(tables){const vals=PHYSICAL_TABLE_IDS.map(id=>({id,...((tables||{})[id]||{}),status:operationalTableStatus((tables||{})[id]||{})}));const counts={total:PHYSICAL_TABLE_IDS.length,seated:0,reserved:0,cleaning:0,ready:0,currentGuests:0};vals.forEach(x=>{counts[x.status]=(counts[x.status]||0)+1;if(x.status==='seated'&&!x.secondaryOf)counts.currentGuests+=Number(x.partyPeople||x.people)||0});counts.occupied=counts.seated+counts.reserved;counts.load=counts.total?counts.occupied/counts.total:0;counts.active=vals.filter(x=>x.status==='seated');return counts}
function boardStaff(boards){const key=boardKeyNow(),board=boards?.[key],rows=asArray(board?.rows,30).filter(Boolean);let active=0,onBreak=0,cut=0;const people=[];rows.forEach(r=>{const name=txt(r.server).trim();if(!name)return;const reason=txt(r.cutReason).toUpperCase();let state=r.active!==false?'ACTIVE':reason==='BREAK'?'BREAK':'CUT';if(state==='ACTIVE')active++;else if(state==='BREAK')onBreak++;else cut++;people.push({name,section:txt(r.section),workShift:txt(r.workShift),state})});return{key,active,onBreak,cut,people}}
function reservationsList(raw){return Object.entries(raw||{}).map(([id,r])=>({id,...(r||{}),people:Number(r?.people)||0})).filter(r=>r.date&&r.time&&!/cancel|canceled|done/i.test(txt(r.status)))}
async function fetchJson(path){const r=await fetch(`${BOARD_ROOT}/${path}.json`,{cache:'no-store'});if(!r.ok)throw new Error(`Quick Board HTTP ${r.status} • ${path}`);return r.json()}
export async function fetchQuickBoardData(){const d=today(),amKey=`${d}_AM`,pmKey=`${d}_PM`;const [analytics,am,pm,reservations,tables]=await Promise.all([fetchJson('analyticsV1'),fetchJson(`rotationBoardV31/${amKey}`).catch(()=>null),fetchJson(`rotationBoardV31/${pmKey}`).catch(()=>null),fetchJson('reservationsV34').catch(()=>({})),fetchJson('tables').catch(()=>({}))]);const boards={};if(am)boards[amKey]=am;if(pm)boards[pmKey]=pm;return{analytics:analytics||{},boards,reservations:reservationsList(reservations),tables:tables||{},events:mergeEvents(analytics||{},boards),floor:liveFloor(tables||{}),staff:boardStaff(boards),fetchedAt:Date.now()}}
export async function fetchQuickBoardLiveData(previous={}){const d=today(),amKey=`${d}_AM`,pmKey=`${d}_PM`;const [am,pm,reservations,tables,archAm,archPm]=await Promise.all([fetchJson(`rotationBoardV31/${amKey}`).catch(()=>null),fetchJson(`rotationBoardV31/${pmKey}`).catch(()=>null),fetchJson('reservationsV34').catch(()=>({})),fetchJson('tables').catch(()=>({})),fetchJson(`analyticsV1/${amKey}`).catch(()=>null),fetchJson(`analyticsV1/${pmKey}`).catch(()=>null)]);const analytics={...(previous?.analytics||{})};if(archAm)analytics[amKey]=archAm;if(archPm)analytics[pmKey]=archPm;const boards={};if(am)boards[amKey]=am;if(pm)boards[pmKey]=pm;return{...previous,analytics,boards,reservations:reservationsList(reservations),tables:tables||{},events:mergeEvents(analytics,boards),floor:liveFloor(tables||{}),staff:boardStaff(boards),fetchedAt:Date.now(),liveFetchedAt:Date.now()}}
export function subscribeQuickBoardLive(onChange,onStatus){const d=today(),paths=[`rotationBoardV31/${d}_AM`,`rotationBoardV31/${d}_PM`,`analyticsV1/${d}_AM`,`analyticsV1/${d}_PM`,'tables','reservationsV34'];const streams=[];let closed=false,timer=null;const signal=(path,type)=>{if(closed)return;clearTimeout(timer);timer=setTimeout(()=>onChange?.({path,type,at:Date.now()}),250)};for(const path of paths){try{const es=new EventSource(`${BOARD_ROOT}/${path}.json`);es.onopen=()=>onStatus?.({state:'live',path});es.addEventListener('put',()=>signal(path,'put'));es.addEventListener('patch',()=>signal(path,'patch'));es.addEventListener('cancel',e=>onStatus?.({state:'error',path,error:e}));es.addEventListener('auth_revoked',e=>onStatus?.({state:'error',path,error:e}));es.onerror=()=>onStatus?.({state:'reconnecting',path});streams.push(es)}catch(e){onStatus?.({state:'error',path,error:e})}}return()=>{closed=true;clearTimeout(timer);streams.forEach(es=>{try{es.close()}catch{}})}}
export function eventsForDate(data,date){return(data?.events||[]).filter(e=>e.date===date)}
export function reservationsForDate(data,date){return(data?.reservations||[]).filter(r=>r.date===date)}
export function recordedDates(data){return[...new Set((data?.events||[]).map(e=>e.date).filter(Boolean))].sort()}
