export const GOOGLE_PLACE_ID='ChIJmxtIi39rYogRSvt3otrmncA';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const DAYS=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'];
function parse12(label){const m=String(label||'').trim().match(/^(\d{1,2})(?::(\d{2}))?\s*(AM|PM)$/i);if(!m)return null;let h=+m[1]%12;if(m[3].toUpperCase()==='PM')h+=12;return h*60+(+m[2]||0)}
function dayKey(date){const [y,m,d]=date.split('-').map(Number);return DAYS[new Date(Date.UTC(y,m-1,d,12)).getUTCDay()]}
function pointAt(external,date,start){const rows=external?.weekly?.[dayKey(date)]||[];if(!rows.length)return null;const points=rows.map(x=>({...x,min:parse12(x.time)})).filter(x=>x.min!=null).sort((a,b)=>a.min-b.min);if(!points.length)return null;let a=points[0],b=points[0];for(let i=0;i<points.length;i++){if(points[i].min<=start)a=points[i];if(points[i].min>=start){b=points[i];break}b=points[i]}
 const sa=Number(a.busynessScore);const sb=Number(b.busynessScore);if(!Number.isFinite(sa)&&!Number.isFinite(sb))return null;if(a.min===b.min||!Number.isFinite(sb))return Number.isFinite(sa)?sa:sb;const t=clamp((start-a.min)/(b.min-a.min),0,1);return sa+(sb-sa)*t}
function recompute(f,slots){const peak=Math.max(.1,...slots.map(s=>s.tables));slots=slots.map(s=>{const trafficIndex=Math.round(clamp(s.tables/peak*100,0,100)),level=trafficIndex>=96?'Peak':trafficIndex>=78?'Very Busy':trafficIndex>=58?'Busy':trafficIndex>=34?'Normal':'Slow';return{...s,trafficIndex,level}});const hm=new Map;for(const s of slots){const h=Math.floor(s.start/60),x=hm.get(h)||{hour:h,tables:0,guests:0,reservations:0,confidence:0,n:0};x.tables+=s.tables;x.guests+=s.guests;x.reservations+=s.reservations||0;x.confidence+=s.confidence||f.confidence;x.n++;hm.set(h,x)}const hourly=[...hm.values()].sort((a,b)=>a.hour-b.hour).map(x=>({...x,label:`${x.hour%12||12}:00 ${x.hour<12?'AM':'PM'}`,confidence:Math.round(x.confidence/x.n)}));const peakSlot=slots.slice().sort((a,b)=>b.tables-a.tables||b.guests-a.guests)[0]||null,slowSlot=slots.filter(x=>x.tables>0).sort((a,b)=>a.tables-b.tables)[0]||null;return{...f,slots,hourly,totalTables:slots.reduce((a,s)=>a+s.tables,0),totalGuests:slots.reduce((a,s)=>a+s.guests,0),peakSlot,slowSlot,confidence:Math.round(slots.reduce((a,s)=>a+(s.confidence||0),0)/Math.max(1,slots.length))}}
export async function fetchGoogleLive(settings={}){const endpoint=String(settings.externalEndpoint||'/api/google-live').trim();if(!endpoint)return{ok:false,configured:false,error:'External endpoint not configured'};try{const u=new URL(endpoint,location.href);u.searchParams.set('place_id',GOOGLE_PLACE_ID);u.searchParams.set('_',String(Date.now()));const r=await fetch(u.toString(),{cache:'no-store',headers:{'Accept':'application/json'}});const j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)return{ok:false,configured:true,error:j.error||`Google Live HTTP ${r.status}`,fetchedAt:Date.now()};return{...j,ok:true,configured:true}}catch(e){return{ok:false,configured:true,error:e.message||String(e),fetchedAt:Date.now()}}}
export function blendForecastWithGoogle(f,external,settings={}){if(!f||!external?.ok||!external.weekly)return{...f,external:{connected:false,applied:false}};const patternWeight=clamp(Number(settings.externalPatternWeight??18)/100,0,.5),liveWeight=clamp(Number(settings.externalLiveWeight??35)/100,0,.7);const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const nowParts=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));const nowTotal=+nowParts.hour*60+(+nowParts.minute);let applied=0;const slots=f.slots.map(s=>{const g=pointAt(external,f.date,s.start);let pf=1;if(Number.isFinite(g)){pf=clamp(1+((g-(s.trafficIndex||0))/100)*patternWeight,.86,1.14);applied++}let lf=1;if(f.date===today&&s.start>nowTotal&&s.start<=nowTotal+120&&Number.isFinite(external.liveScore)&&Number.isFinite(external.usualScore)){const delta=(external.liveScore-external.usualScore)/100,decay=Math.exp(-(s.start-nowTotal)/150);lf=clamp(1+delta*liveWeight*decay,.78,1.30)}const mult=pf*lf;return{...s,tables:s.tables*mult,guests:s.guests*mult,rangeLow:s.rangeLow*mult,rangeHigh:s.rangeHigh*mult,googleTypicalScore:Number.isFinite(g)?Math.round(g):null,googlePatternFactor:pf,googleLiveFactor:lf,confidence:Math.min(96,(s.confidence||f.confidence)+(Number.isFinite(g)?3:0)+(lf!==1?2:0))}});const r=recompute(f,slots);return{...r,external:{connected:true,applied:applied>0,source:external.source,liveScore:external.liveScore,usualScore:external.usualScore,info:external.info,timeSpent:external.timeSpent,fetchedAt:external.fetchedAt,patternWeight,liveWeight}}}
